#!/usr/bin/env bash
# Build the dsh-pager Android app without Gradle:
#   aapt2 -> javac -> d8 -> zipalign -> apksigner  (~30 KB APK)
#
#   bash build.sh            # private build: presets the server from local.properties
#   bash build.sh public     # release build: no preset (the app asks on first launch), WebView debugging off
#   bash build.sh install    # private build + `adb install -r`
#
# Needs an Android SDK (build-tools 34.0.0, platform android-34) and JDK 17.
# Set ANDROID_SDK (or ANDROID_HOME) and JDK_HOME (or JAVA_HOME), in the
# environment or in local.properties.
#
# local.properties (git-ignored), all optional:
#   DSH_DEFAULT_SERVER=https://dsh.example.com:8443
#   ANDROID_SDK=/path/to/android-sdk
#   JDK_HOME=/path/to/jdk-17
#
# Signing: keystore/dsh.jks + keystore/password.txt (git-ignored) are created
# on the first build. KEEP THEM: an update must be signed with the same key,
# otherwise Android refuses to install over the existing app.
set -euo pipefail

VERSION_CODE=9
VERSION_NAME=1.4.0

MODE=${1:-private}
SRC=$(cd "$(dirname "$0")" && pwd)
prop() { [ -f "$SRC/local.properties" ] && sed -n "s/^$1=//p" "$SRC/local.properties" | tr -d '\r' | head -1 || true; }
SDK=${ANDROID_SDK:-${ANDROID_HOME:-$(prop ANDROID_SDK)}}
JDK=${JDK_HOME:-${JAVA_HOME:-$(prop JDK_HOME)}}
[ -n "$SDK" ] && [ -d "$SDK/build-tools/34.0.0" ] || { echo "Set ANDROID_SDK (needs build-tools/34.0.0 and platforms/android-34)"; exit 1; }
[ -n "$JDK" ] && [ -d "$JDK/bin" ] || { echo "Set JDK_HOME to a JDK 17"; exit 1; }
BT=$SDK/build-tools/34.0.0
PLATFORM=$SDK/platforms/android-34/android.jar
ADB=${ADB:-adb}
WORK=${WORK:-${TMPDIR:-/tmp}/dsh-pager-build}
# Native tools are aapt2.exe etc. on Windows and aapt2 elsewhere.
tool() { if [ -x "$BT/$1.exe" ]; then echo "$BT/$1.exe"; else echo "$BT/$1"; fi; }
OUT=$SRC/out
KS=$SRC/keystore/dsh.jks
KSPASS_FILE=$SRC/keystore/password.txt
# Git Bash rewrites bare POSIX paths for native tools, but not ones behind a
# prefix like "file:/e/...", which Java then resolves against the current
# drive. Hand the signer explicit Windows paths.
win() { if command -v cygpath >/dev/null 2>&1; then cygpath -w "$1"; else echo "$1"; fi; }

SERVER=""
[ "$MODE" != "public" ] && SERVER=$(prop DSH_DEFAULT_SERVER)

# The project path may contain non-ASCII characters; every tool runs from an
# ASCII-only work dir and only the signed APK is copied back.
rm -rf "$WORK"
mkdir -p "$WORK/gen/com/agenthub/dsh" "$WORK/classes" "$WORK/dex" "$OUT" "$SRC/keystore"
cp -r "$SRC/res" "$SRC/assets" "$SRC/src" "$SRC/AndroidManifest.xml" "$WORK/"
cd "$WORK"

if [ -n "$SERVER" ]; then
  esc=$(printf '%s' "$SERVER" | sed 's/[&|\\]/\\&/g')
  sed -i "s|<string name=\"default_server\" translatable=\"false\"></string>|<string name=\"default_server\" translatable=\"false\">$esc</string>|" res/values/config.xml
  echo "      preset server: $SERVER"
else
  echo "      no preset server (asks on first launch)"
fi
DEBUG=true
[ "$MODE" = "public" ] && DEBUG=false
printf 'package com.agenthub.dsh;\n\n/** Generated by build.sh. */\nfinal class BuildInfo {\n    static final String VERSION = "%s";\n    static final int VERSION_CODE = %s;\n    /** WebView remote debugging: private builds only. */\n    static final boolean WEBVIEW_DEBUG = %s;\n\n    private BuildInfo() {\n    }\n}\n' "$VERSION_NAME" "$VERSION_CODE" "$DEBUG" > gen/com/agenthub/dsh/BuildInfo.java

echo "[1/6] aapt2 compile + link"
"$(tool aapt2)" compile --dir res -o res.zip
"$(tool aapt2)" link -I "$PLATFORM" --manifest AndroidManifest.xml -A assets \
  --min-sdk-version 29 --target-sdk-version 34 \
  --version-code "$VERSION_CODE" --version-name "$VERSION_NAME" \
  --java gen -o app.unsigned.apk res.zip

echo "[2/6] javac"
"$JDK/bin/javac" -J-Duser.language=en -encoding UTF-8 --release 11 -nowarn -cp "$PLATFORM" -d classes \
  $(find src gen -name '*.java')

echo "[3/6] d8"
"$JDK/bin/java" -cp "$BT/lib/d8.jar" com.android.tools.r8.D8 --release --min-api 29 \
  --lib "$PLATFORM" --output dex $(find classes -name '*.class')
(cd dex && "$(tool aapt)" add ../app.unsigned.apk classes.dex >/dev/null)

echo "[4/6] zipalign"
"$(tool zipalign)" -f -p 4 app.unsigned.apk app.aligned.apk

echo "[5/6] sign"
if [ ! -f "$KS" ]; then
  head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' > "$KSPASS_FILE"
  "$JDK/bin/keytool" -genkeypair -keystore "$(win "$KS")" -alias dsh -keyalg RSA -keysize 2048 \
    -validity 36500 -storepass "$(cat "$KSPASS_FILE")" -keypass "$(cat "$KSPASS_FILE")" \
    -dname "CN=dsh-pager" >/dev/null 2>&1
  echo "      new signing key: $KS"
fi
NAME=DSH.apk
[ "$MODE" = "public" ] && NAME=dsh-pager-v$VERSION_NAME.apk
"$JDK/bin/java" -jar "$BT/lib/apksigner.jar" sign --ks "$(win "$KS")" --ks-key-alias dsh \
  --ks-pass "file:$(win "$KSPASS_FILE")" --out "$(win "$OUT/$NAME")" app.aligned.apk
"$JDK/bin/java" -jar "$BT/lib/apksigner.jar" verify "$(win "$OUT/$NAME")"
rm -f "$OUT/$NAME.idsig"
# What the plugin offers for in-app updates (GET /m/api/app/latest); the app checks the SHA-256.
SHA=$(sha256sum "$OUT/$NAME" | cut -d' ' -f1)
printf '{"versionCode":%s,"versionName":"%s","sha256":"%s","size":%s,"built":"%s"}\n' \
  "$VERSION_CODE" "$VERSION_NAME" "$SHA" "$(wc -c < "$OUT/$NAME")" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$OUT/$NAME.json"

echo "[6/6] done: $OUT/$NAME ($(wc -c < "$OUT/$NAME") bytes, v$VERSION_NAME)"

if [ "$MODE" = "install" ]; then
  "$ADB" install -r "$OUT/$NAME"
fi
